/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is auto-generated by Next.js the first time you run `npm run dev`
// or `npm run build`. It's committed here so the project type-checks even
// before that first run. Do not edit it by hand.
