/**
 * Import a game export (like the "RENEWABLE TEMPLATE" JSON) into SQL seed
 * data matching supabase/migrations/00000000000001_init.sql.
 *
 * This does NOT talk to a database directly — it reads the source JSON and
 * writes a plain .sql file to content/seed/seed.sql, which you (or a future
 * Claude session) can run against a real Supabase project once one exists
 * (paste it into the SQL editor, or `psql` / `supabase db execute` it).
 * Keeping it as a file-to-file script means it can be reviewed before it
 * ever touches a database, and it needs zero extra packages to run.
 *
 * Usage:
 *   tsx scripts/import-template.ts [path-to-export.json]
 *
 * Defaults to content/source/renewable-template-export.json.
 */

import { randomUUID } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, "..");

const SOURCE_PATH =
  process.argv[2] ??
  path.join(ROOT, "content", "source", "renewable-template-export.json");
const SEED_DIR = path.join(ROOT, "content", "seed");
const PHOTOS_DIR = path.join(SEED_DIR, "photos");
const OUT_SQL_PATH = path.join(SEED_DIR, "seed.sql");

// ---------------------------------------------------------------------------
// SQL formatting helpers
// ---------------------------------------------------------------------------

function sqlNum(n: number | null | undefined): string {
  return n === null || n === undefined || Number.isNaN(n) ? "null" : String(n);
}

function sqlBool(b: boolean | null | undefined): string {
  return b === null || b === undefined ? "null" : b ? "true" : "false";
}

function sqlUuid(id: string | null | undefined): string {
  return id ? `'${id}'` : "null";
}

/** Dollar-quote free text so we never have to hand-escape quotes/HTML. */
function dq(text: string | null | undefined): string {
  if (text === null || text === undefined) return "null";
  let tag = "q";
  let i = 0;
  while (text.includes(`$${tag}$`)) {
    i += 1;
    tag = `q${i}`;
  }
  return `$${tag}$${text}$${tag}$`;
}

function sqlTextArray(arr: string[] | null | undefined): string {
  if (!arr || arr.length === 0) return "'{}'::text[]";
  return "ARRAY[" + arr.map(dq).join(", ") + "]::text[]";
}

/**
 * Description entries are usually plain strings, but a handful of assets
 * (exploration prospects) use `{ text, bold }` objects instead so the UI can
 * bold part of a line. Bold styling isn't part of the new schema (that's a
 * display concern, not data) — a leading "**" marks it was bold in the
 * source, cheap to strip or render later if it turns out to matter.
 */
function normalizeDescription(items: unknown[] | null | undefined): string[] {
  if (!items) return [];
  return items.map((item) => {
    if (typeof item === "string") return item;
    if (item && typeof item === "object" && "text" in item) {
      const { text, bold } = item as { text: string; bold?: boolean };
      return bold ? `**${text}**` : text;
    }
    return String(item);
  });
}

const statements: string[] = [];
const counts: Record<string, number> = {};

function insertMany(table: string, columns: string[], rows: string[][]) {
  if (rows.length === 0) return;
  counts[table] = (counts[table] ?? 0) + rows.length;
  statements.push(`insert into ${table} (${columns.join(", ")}) values`);
  statements.push(rows.map((r) => `  (${r.join(", ")})`).join(",\n") + ";");
  statements.push("");
}

function slugify(name: string): string {
  return name
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
}

function writePhoto(dataUrl: string, id: string): string | null {
  const match = /^data:image\/(\w+);base64,(.+)$/.exec(dataUrl);
  if (!match) return null;
   const [, ext, base64] = match;
  if (!ext || !base64) return null; // the regex guarantees these, but satisfies strict TS
  const fileName = `${id}.${ext === "jpeg" ? "jpg" : ext}`;
  mkdirSync(PHOTOS_DIR, { recursive: true });
  writeFileSync(path.join(PHOTOS_DIR, fileName), Buffer.from(base64, "base64"));
  return `photos/${fileName}`;
}

// ---------------------------------------------------------------------------
// Load source
// ---------------------------------------------------------------------------

if (!existsSync(SOURCE_PATH)) {
  console.error(`Source file not found: ${SOURCE_PATH}`);
  process.exit(1);
}

const raw = JSON.parse(readFileSync(SOURCE_PATH, "utf8"));
const tpl = raw.template;

const templateId = randomUUID();

statements.push("-- Generated by scripts/import-template.ts — do not edit by hand.");
statements.push(`-- Source: ${path.relative(ROOT, SOURCE_PATH)}`);
statements.push("begin;");
statements.push("");

insertMany(
  "game_templates",
  ["id", "name", "map_image", "theme", "field_optimization"],
  [
    [
      sqlUuid(templateId),
      dq(raw.name),
      dq(raw.mapImage ?? null),
      dq(raw.theme ?? null),
      sqlBool(raw.fieldOptimization ?? false),
    ],
  ],
);

// ---------------------------------------------------------------------------
// Areas
// ---------------------------------------------------------------------------

const areaIdByName = new Map<string, string>();

const areaRows: string[][] = [];
for (const a of tpl.areas ?? []) {
  areaIdByName.set(a.name, a.id);
  areaRows.push([
    sqlUuid(a.id),
    sqlUuid(templateId),
    dq(a.name),
    dq(a.type),
    dq(a.productionUnit),
    sqlBool(a.randomizePrice),
    sqlNum(a.priceDrift),
    sqlNum(a.priceStandardDeviation),
    sqlNum(a.priceInflation),
    sqlNum(a.priceMean),
    sqlNum(a.minPrice),
    sqlNum(a.maxPrice),
    sqlNum(a.merchantPrice),
    sqlNum(a.co2EmittedPerProduction),
  ]);
}
insertMany(
  "areas",
  [
    "id",
    "template_id",
    "name",
    "type",
    "production_unit",
    "randomize_price",
    "price_drift",
    "price_standard_deviation",
    "price_inflation",
    "price_mean",
    "min_price",
    "max_price",
    "merchant_price",
    "co2_emitted_per_production",
  ],
  areaRows,
);

function areaIdFor(name: string | null | undefined): string | null {
  if (!name) return null;
  return areaIdByName.get(name) ?? null;
}

// ---------------------------------------------------------------------------
// Assets (+ year financials, production, financing, offtakes)
// ---------------------------------------------------------------------------

const assetIdByName = new Map<string, string>();

const assetRows: string[][] = [];
const yearFinancialRows: string[][] = [];
const productionRows: string[][] = [];
const financingRows: string[][] = [];
const offtakeRows: string[][] = [];

for (const a of tpl.assets ?? []) {
  assetIdByName.set(a.name, a.id);
  assetIdByName.set(a.name.trim(), a.id);

  assetRows.push([
    sqlUuid(a.id),
    sqlUuid(templateId),
    dq(a.name),
    dq(a.assetType),
    sqlNum(a.xCoordinate),
    sqlNum(a.yCoordinate),
    sqlNum(a.capacity ?? 1),
    sqlNum(a.capacityFactor),
    sqlNum(a.risk ?? 0),
    sqlNum(a.minimumAccessCost ?? 0),
    sqlNum(a.minimumBid ?? 0),
    sqlBool(a.isVisible ?? true),
    sqlBool(a.isExploration ?? false),
    dq(a.taxType ?? null),
    sqlBool(a.royalty ?? false),
    sqlNum(a.electrificationStart),
    sqlNum(a.availableFromYear),
    dq(a.iconName ?? null),
    dq(a.capexIconName ?? null),
    dq(a.mapName ?? null),
    sqlTextArray(normalizeDescription(a.description)),
  ]);

  const capex: number[] = a.capex ?? [];
  const opex: number[] = a.opex ?? [];
  const devex: number[] = a.devex ?? [];
  const maxLen = Math.max(capex.length, opex.length, devex.length);
  for (let i = 0; i < maxLen; i++) {
    yearFinancialRows.push([
      sqlUuid(randomUUID()),
      sqlUuid(a.id),
      sqlNum(i + 1),
      sqlNum(capex[i] ?? 0),
      sqlNum(opex[i] ?? 0),
      sqlNum(devex[i] ?? 0),
    ]);
  }

  for (const profile of a.productionProfiles ?? []) {
    const areaId = profile.areaId ?? areaIdFor(profile.areaName);
    if (!areaId) continue;
    const production: number[] = profile.production ?? [];
    production.forEach((value, i) => {
      productionRows.push([
        sqlUuid(randomUUID()),
        sqlUuid(a.id),
        sqlUuid(areaId),
        sqlNum(i + 1),
        sqlNum(value ?? 0),
      ]);
    });
  }

  for (const loan of a.availableLoans ?? []) {
    // Some assets in the source export reuse the exact same loan `id`
    // across different assets (it looks like a shared option template
    // referenced by id, not an asset-specific row) — always mint a fresh id
    // here since asset_financing_options is asset-specific in this schema.
    financingRows.push([
      sqlUuid(randomUUID()),
      sqlUuid(a.id),
      dq(loan.lender),
      sqlNum(loan.interestRatePercent),
      sqlNum(loan.financedPercent),
      sqlBool(loan.requiresSupport ?? false),
      sqlNum(loan.downPaymentYears ?? 0),
    ]);
  }

  for (const offtake of a.availableOfftakes ?? []) {
    offtakeRows.push([
      sqlUuid(randomUUID()),
      sqlUuid(a.id),
      dq(offtake.name),
      dq(offtake.offtakeType),
      sqlNum(offtake.supportPeriod),
      sqlNum(offtake.supportPrice),
    ]);
  }
}

insertMany(
  "assets",
  [
    "id",
    "template_id",
    "name",
    "asset_type",
    "x_coordinate",
    "y_coordinate",
    "capacity",
    "capacity_factor",
    "risk",
    "minimum_access_cost",
    "minimum_bid",
    "is_visible",
    "is_exploration",
    "tax_type",
    "royalty",
    "electrification_start",
    "available_from_year",
    "icon_name",
    "capex_icon_name",
    "map_name",
    "description",
  ],
  assetRows,
);
insertMany(
  "asset_year_financials",
  ["id", "asset_id", "year", "capex", "opex", "devex"],
  yearFinancialRows,
);
insertMany(
  "asset_production",
  ["id", "asset_id", "area_id", "year", "production"],
  productionRows,
);
insertMany(
  "asset_financing_options",
  [
    "id",
    "asset_id",
    "lender",
    "interest_rate_percent",
    "financed_percent",
    "requires_support",
    "down_payment_years",
  ],
  financingRows,
);
insertMany(
  "asset_offtake_options",
  ["id", "asset_id", "name", "offtake_type", "support_period", "support_price"],
  offtakeRows,
);

// ---------------------------------------------------------------------------
// Interventions (+ effects, + CSR choices)
// ---------------------------------------------------------------------------

const interventionRows: string[][] = [];
const effectRows: string[][] = [];
const choiceRows: string[][] = [];

for (const iv of tpl.interventions ?? []) {
  const key = slugify(iv.name);
  const photoPath = iv.photo ? writePhoto(iv.photo, iv.id) : null;
  const dependsOn: string[] = (iv.when ?? []).map((w: string) => slugify(w));

  interventionRows.push([
    sqlUuid(iv.id),
    sqlUuid(templateId),
    dq(key),
    dq(iv.name),
    sqlNum(iv.year),
    dq(iv.recipients ?? "ALL"),
    dq(iv.subject ?? null),
    dq(iv.message ?? null),
    dq(photoPath),
    sqlTextArray(dependsOn),
  ]);

  for (const effect of iv.effects ?? []) {
    const effectId = effect.id ?? randomUUID();
    effectRows.push([
      sqlUuid(effectId),
      sqlUuid(iv.id),
      dq(effect.type),
      sqlNum(effect.amount ?? 0),
      sqlUuid(areaIdFor(effect.areaName)),
    ]);
    for (const choice of effect.choices ?? []) {
      choiceRows.push([
        sqlUuid(randomUUID()),
        sqlUuid(effectId),
        dq(choice.text),
        dq(choice.type),
        sqlBool(choice.requiresAmount ?? false),
      ]);
    }
  }
}

insertMany(
  "interventions",
  [
    "id",
    "template_id",
    "key",
    "name",
    "year",
    "recipients",
    "subject",
    "message",
    "photo_path",
    "depends_on",
  ],
  interventionRows,
);
insertMany(
  "intervention_effects",
  ["id", "intervention_id", "effect_type", "amount", "area_id"],
  effectRows,
);
insertMany(
  "intervention_effect_choices",
  ["id", "effect_id", "text", "choice_type", "requires_amount"],
  choiceRows,
);

// ---------------------------------------------------------------------------
// Asset interventions (+ year financials, production, price effects)
// ---------------------------------------------------------------------------

const assetInterventionRows: string[][] = [];
const aiYearFinancialRows: string[][] = [];
const aiProductionRows: string[][] = [];
const aiPriceEffectRows: string[][] = [];
let unmatchedAssetNames = 0;

for (const ai of tpl.assetInterventions ?? []) {
  const assetId = ai.assetName ? assetIdByName.get(ai.assetName) ?? null : null;
  if (ai.assetName && !assetId) unmatchedAssetNames += 1;
  const photoPath = ai.photo ? writePhoto(ai.photo, ai.id) : null;

  assetInterventionRows.push([
    sqlUuid(ai.id),
    sqlUuid(templateId),
    sqlUuid(assetId),
    dq(ai.assetName ?? null),
    dq(ai.name),
    sqlNum(ai.year),
    dq(ai.subject ?? null),
    dq(ai.message ?? null),
    dq(ai.choice ?? null),
    dq(photoPath),
    sqlBool(ai.isAdditive),
    sqlNum(ai.capacity),
    sqlNum(ai.capacityFactor),
    dq(ai.taxType ?? null),
    sqlBool(ai.royalty),
    sqlNum(ai.electrificationTime),
    sqlBool(ai.simulateAlternatives ?? true),
    dq(ai.dependency ?? null),
  ]);

  const capex: number[] = ai.capex ?? [];
  const opex: number[] = ai.opex ?? [];
  const devex: number[] = ai.devex ?? [];
  const maxLen = Math.max(capex.length, opex.length, devex.length);
  for (let i = 0; i < maxLen; i++) {
    aiYearFinancialRows.push([
      sqlUuid(randomUUID()),
      sqlUuid(ai.id),
      sqlNum(i + 1),
      sqlNum(capex[i] ?? 0),
      sqlNum(opex[i] ?? 0),
      sqlNum(devex[i] ?? 0),
    ]);
  }

  for (const profile of ai.productionProfiles ?? []) {
    const areaId = profile.areaId ?? areaIdFor(profile.areaName);
    if (!areaId) continue;
    const production: number[] = profile.production ?? [];
    production.forEach((value, i) => {
      aiProductionRows.push([
        sqlUuid(randomUUID()),
        sqlUuid(ai.id),
        sqlUuid(areaId),
        sqlNum(i + 1),
        sqlNum(value ?? 0),
      ]);
    });
  }

  for (const [areaName, effect] of Object.entries(ai.prices ?? {})) {
    const areaId = areaIdFor(areaName);
    if (!areaId) continue;
    const priceDiff = (effect as { priceDiff?: number }).priceDiff ?? 0;
    aiPriceEffectRows.push([
      sqlUuid(randomUUID()),
      sqlUuid(ai.id),
      sqlUuid(areaId),
      sqlNum(priceDiff),
    ]);
  }
}

insertMany(
  "asset_interventions",
  [
    "id",
    "template_id",
    "asset_id",
    "asset_name",
    "name",
    "year",
    "subject",
    "message",
    "choice_text",
    "photo_path",
    "is_additive",
    "capacity",
    "capacity_factor",
    "tax_type",
    "royalty",
    "electrification_time",
    "simulate_alternatives",
    "dependency",
  ],
  assetInterventionRows,
);
insertMany(
  "asset_intervention_year_financials",
  ["id", "asset_intervention_id", "year", "capex", "opex", "devex"],
  aiYearFinancialRows,
);
insertMany(
  "asset_intervention_production",
  ["id", "asset_intervention_id", "area_id", "year", "production"],
  aiProductionRows,
);
insertMany(
  "asset_intervention_price_effects",
  ["id", "asset_intervention_id", "area_id", "price_diff"],
  aiPriceEffectRows,
);

statements.push("commit;");

// ---------------------------------------------------------------------------
// Write output + report
// ---------------------------------------------------------------------------

mkdirSync(SEED_DIR, { recursive: true });
writeFileSync(OUT_SQL_PATH, statements.join("\n") + "\n");

console.log(`Wrote ${path.relative(ROOT, OUT_SQL_PATH)}`);
console.log("");
console.log("Row counts:");
for (const [table, count] of Object.entries(counts)) {
  console.log(`  ${table.padEnd(32)} ${count}`);
}
if (unmatchedAssetNames > 0) {
  console.log("");
  console.log(
    `Warning: ${unmatchedAssetNames} asset intervention(s) referenced an assetName with no matching asset — imported with asset_id = null, asset_name kept for reference.`,
  );
}
console.log("");
console.log(
  "Note: the source export's 'teams' were not imported — in the new schema teams belong to a game_session, created by the facilitator console (Phase 3), not to the template. This also means the leftover test bid on 'Tempest' by 'Everon' was dropped, as intended.",
);
